### ISSUE TITLE
关于字节对齐的疑问

### ISSUE THREAD

**Issue by whj4674672** [mysterywolf/rt_memcpy_cm#1]
例如，我在使用 `stm32 sdio` 的时候会考虑字节对齐的问题，https://github.com/RT-Thread/rt-thread/pull/4015

不知道这个汇编版本的 `memcpy` 需要手动做对齐吗？

**Comment by mysterywolf** [comment]
内部已经考虑了4字节对齐，非4字节对齐地址时是一个字节一个字节的拷贝，只有等到4字节对齐时才开始大批量复制 比如这里：        CMP         R3, #1                  ; copy 1 byte (to align to the next 16-bit boundary)。在开发者大会上不是有一个10分钟挑战的小项目嘛，那个项目就是用sd卡拷贝一个文件拼谁优化的最快，我把这段代码贴上去了，运行完全没有问题，速度提高了大概500ms，因为memcpy对于sd卡拷贝来说不是大头，所以优化效果没有显著提高。
